# Generated by Django 5.2.4 on 2025-08-01 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Brief biography or description', max_length=500)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Personal website or portfolio')),
                ('github_username', models.CharField(blank=True, help_text='GitHub username', max_length=100)),
                ('linkedin_profile', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter handle (without @)', max_length=100)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-1 years)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3-5 years)'), ('expert', 'Expert (5+ years)')], default='beginner', help_text='Overall experience level in technology/programming', max_length=20)),
                ('learning_style', models.CharField(choices=[('visual', 'Visual Learner'), ('auditory', 'Auditory Learner'), ('kinesthetic', 'Kinesthetic Learner'), ('reading', 'Reading/Writing Learner'), ('mixed', 'Mixed Learning Style')], default='mixed', help_text='Preferred learning style', max_length=20)),
                ('interests', models.CharField(blank=True, help_text='Comma-separated list of interests and topics', max_length=500)),
                ('goals', models.TextField(blank=True, help_text='Learning goals and career objectives')),
                ('time_zone', models.CharField(default='UTC', help_text="User's time zone", max_length=50)),
                ('weekly_learning_hours', models.PositiveIntegerField(default=5, help_text='Target hours per week for learning')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('public_profile', models.BooleanField(default=True, help_text='Make profile visible to other users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Name of the skill (e.g., Python, JavaScript, Machine Learning)', max_length=100)),
                ('proficiency_level', models.CharField(choices=[('novice', 'Novice'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='novice', help_text='Current proficiency level in this skill', max_length=20)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0.0, help_text='Years of experience with this skill', max_digits=4)),
                ('verified', models.BooleanField(default=False, help_text='Whether this skill has been verified through assessments')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this skill')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill',
                'verbose_name_plural': 'User Skills',
                'ordering': ['-proficiency_level', 'skill_name'],
                'unique_together': {('user', 'skill_name')},
            },
        ),
    ]
