# Generated by Django 5.2.4 on 2025-08-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlearningprogress',
            name='progress_percentage',
        ),
    ]
